"""Generate synthetic test files for the PaleoRigor pilot usability session.

All data are computer-generated and carry no biological meaning. They exist
only to give a participant realistic-looking inputs to work with. Fixed seed,
so the session can be repeated with identical files.
"""
from __future__ import annotations

import random
from pathlib import Path

OUT = Path(__file__).resolve().parent / "fixtures"
OUT.mkdir(exist_ok=True)
rng = random.Random(20260923)

BASES = "ACGT"
QUAL = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHI"


def quality(n: int, floor: int, ceil: int) -> str:
    return "".join(QUAL[rng.randint(floor, ceil)] for _ in range(n))


def paired_fastq(name: str, n_reads: int) -> None:
    r1, r2 = [], []
    for i in range(1, n_reads + 1):
        length = rng.randint(45, 118)
        seq = "".join(rng.choice(BASES) for _ in range(length))
        if rng.random() < 0.04:
            pos = rng.randrange(length)
            seq = seq[:pos] + "N" + seq[pos + 1 :]
        mate = "".join(rng.choice(BASES) for _ in range(length))
        rid = f"{name}_{i:04d}"
        r1 += [f"@{rid}/1", seq, "+", quality(length, 20, 40)]
        r2 += [f"@{rid}/2", mate, "+", quality(length, 14, 38)]
    (OUT / f"{name}_R1.fastq").write_text("\n".join(r1) + "\n")
    (OUT / f"{name}_R2.fastq").write_text("\n".join(r2) + "\n")


def peptide_table(n_unique: int, n_duplicated: int) -> None:
    aa = "ACDEFGHIKLMNPQRSTVWY"
    uniq = set()
    while len(uniq) < n_unique:
        uniq.add("".join(rng.choice(aa) for _ in range(rng.randint(9, 34))))
    uniq = sorted(uniq)
    rows = [(rng.choice([0, 1]), p) for p in uniq]
    rows += [rows[rng.randrange(len(rows))] for _ in range(n_duplicated)]
    rng.shuffle(rows)
    lines = ["class,peptide"] + [f"{c},{p}" for c, p in rows]
    (OUT / "peptide_screen.csv").write_text("\n".join(lines) + "\n")
    return len(rows), n_duplicated


def metadata_tsv() -> None:
    rows = ["Run_accession\tSample\tLibraryLayout\tScientificName\tCollection_site"]
    sites = ["Cave-A layer 3", "Cave-A layer 5", "Burial-B pit 2", "Lakebed-C core 1"]
    for i in range(1, 13):
        layout = "PAIRED" if i % 3 else "SINGLE"
        rows.append(f"SRR99{i:04d}\tSAMN99{i:04d}\t{layout}\tsediment metagenome\t{rng.choice(sites)}")
    (OUT / "excavation_metadata.tsv").write_text("\n".join(rows) + "\n")


paired_fastq("burial_sediment", 420)
total, dup = peptide_table(360, 44)
metadata_tsv()

readme = f"""# Synthetic test files

These files are COMPUTER-GENERATED for a usability session. They contain no
real biological data and no real accessions. Do not use them for any scientific
purpose or cite any number derived from them as a biological result.

Generated by `../make_fixtures.py` with a fixed seed, so re-running it
reproduces these exact files.

| File | Contents |
| --- | --- |
| `burial_sediment_R1.fastq` | 420 synthetic reads, 45-118 bp, forward mates |
| `burial_sediment_R2.fastq` | 420 synthetic reads, matching reverse mates |
| `peptide_screen.csv` | {total} rows, of which {dup} are exact duplicate sequences |
| `excavation_metadata.tsv` | 12 rows of synthetic run metadata |

Known answer for the observer, not to be shown to the participant:
the peptide table contains {total} rows and {dup} duplicate rows, so a correct
deduplication leaves {total - dup} unique records.
"""
(OUT / "README.md").write_text(readme)
print(readme)
for f in sorted(OUT.iterdir()):
    print(f"{f.name:32s} {f.stat().st_size:>9,} bytes")
